# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
archivesName=swingthrough
group=folk.sisby
modId=swingthrough
modName=SwingThrough
modDescription=Allows targeting living entities through transparent blocks
authors=Sisby folk
homepage=https://modrinth.com/mod/swingthrough
issues=https://github.com/sisby-folk/swingthrough/issues
sources=https://github.com/sisby-folk/swingthrough
license=LGPL-3.0-or-later
# Mod Version
baseVersion=1.0.5
# Branch Metadata
branch=1.21
compatibleVersions=1.20.2, 1.20.3, 1.20.4, 1.20.5, 1.20.6, 1.21, 1.21.1
compatibleLoaders=fabric, quilt, neoforge
